settings:
  title: "Watermelon's Status Page"
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: ai-watermelon.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-watermelon-today # unique identifier
    name: www.watermelon.today
    description: "Watermelon's Website" # default=empty
    url: 'https://www.watermelon.today/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: Google
    name: www.google.com
    description: 'Here is Google.com'
    url: 'https://www.google.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
